version: '3.3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'dev-mongo-db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vaud
      - MONGO_INITDB_ROOT_PASSWORD=vaud2022
    volumes:
      - /mongo-volume:/data/db
    ports:
      - '0.0.0.0:27017:27017'
    networks:
      - mongodb-network

  mongo-express:
    image: 'mongo-express'
    container_name: 'dev-mongo-express'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://vaud:vaud2022@dev-mongo-db:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root2022
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - /mongo-express:/data/db
    networks:
      - mongodb-network
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - mongodb

networks:
  mongodb-network: