server:
  port: 9000
spring:
  application:
    name: todos-app
  data:
    mongodb:
      database: todos-db
      username: vaud
      password: vaud2022
      host: localhost
      port: 27017
      authentication-database: admin
  graphql:
    graphiql:
      enabled: true